apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: skuser01.azurecr.io/delivery:v1
          ports:
            - containerPort: 8080
          env:
            - name: configurl
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: url